name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
          run:
            working-directory: ./src
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: make amount_set_str
      run: make amount_set_str
    - name: run matamikya
      run: ./matamikya
    - name: run as
      run: ./amount_set_str
    - name: zip
      run: zip hw1_sol amount_set_str.c amount_set_str_main.c amount_set_str_tests.c amount_set_str_tests.h matamikya* makefile ../dry.pdf
    - name: setup python
      uses: actions/setup-python@v2
      with:
          python-version: 3.8 #install the python needed
    - name: final check
      run: python ../final_check.py ./src/hw1_sol.zip
  
  
